import { DataTypes } from "sequelize";
import sequelize from "../config/database.js";

const Fragrance = sequelize.define("Fragrance", {
  name: { type: DataTypes.STRING, allowNull: false, defaultValue: "Parfum sans nom" },
  brandId: { type: DataTypes.INTEGER },
  perfumer: { type: DataTypes.STRING },
  inspiration: { type: DataTypes.TEXT },
  concentration: { type: DataTypes.STRING },
  price: { type: DataTypes.FLOAT },
  description: { type: DataTypes.TEXT },
  img: { type: DataTypes.STRING },
  imageUri: { type: DataTypes.STRING },
  topNoteId: { type: DataTypes.INTEGER },
  heartNoteId: { type: DataTypes.INTEGER },
  baseNoteId: { type: DataTypes.INTEGER },
  accords: { type: DataTypes.STRING },
  genre: { type: DataTypes.STRING },
  saison: { type: DataTypes.STRING },
  olfactoryFamilies: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  notes: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  topNotes: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  heartNotes: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  baseNotes: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  seasons: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  occasions: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  rating: { type: DataTypes.FLOAT, validate: { min: 0, max: 10 } },
  sillage: { type: DataTypes.STRING },
  longevity: { type: DataTypes.STRING },
  evolution: { type: DataTypes.JSON, allowNull: false, defaultValue: {} },
  personalNotes: { type: DataTypes.TEXT },
  mainStatus: {
    type: DataTypes.ENUM(
      "to_test",
      "tested",
      "to_retry",
      "owned",
      "planned_purchase",
      "disappointing",
      "too_expensive"
    ),
  },
  isFavorite: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  isWishlist: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  wishlistPriority: { type: DataTypes.ENUM("low", "medium", "high") },
  productUrl: { type: DataTypes.STRING },
  shop: { type: DataTypes.STRING },
  discoveredAt: { type: DataTypes.DATEONLY },
  testedOn: { type: DataTypes.STRING },
  size: { type: DataTypes.STRING },
  formatMl: { type: DataTypes.FLOAT },
  pricePer100ml: { type: DataTypes.FLOAT },
  isDeleted: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
});

export default Fragrance;
